name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main          # triggers the pipeline on every push to main done

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code          # Step 1: pull your code
        uses: actions/checkout@v4

      - name: Setup Pages            # Step 2: configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact        # Step 3: package the site files
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'                  # uploads everything in the root folder

      - name: Deploy to GitHub Pages # Step 4: publish
        id: deployment
        uses: actions/deploy-pages@v4
